name: Salmonia

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python # Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Pythonのバージョン指定

      - name: Install dependencies # 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install python-dotenv
      - name: Run Salmonia # Pythonでデータ取得してアップロード
        env:
          IKSM_SESSION: ${{ secrets.IKSM_SESSION }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          LATEST_JOB_NUM: ${{ secrets.LATEST_JOB_NUM }}
          DEVELOPMENT: ${{ secrets.DEVELOPMENT }}
        run: |
          python main.py
