name: Salmonia

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python # Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Pythonのバージョン指定

      - name: Install dependencies # 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run Salmonia # Pythonでデータ取得してアップロード
        run: |
          python main.py
